"""
core_physics/restrained_stress.py
====================================
Sub-Module 4 (PLANNED): Thermo-Elastic Restrained Stress.

Will compute lateral (restrained) crushing pressure on retaining structures
(e.g., shaft liners, shoring) generated by frost heave confined against a
rigid boundary, using classical thermo-elasticity:

    sigma_restrained = [E / (1 - nu)] * eps_vol_heave      (plane-strain, fully restrained)

    with reduction for partial restraint (structure stiffness ratio, beta in [0,1]):

    sigma_lateral = beta * sigma_restrained     [Pa -> reported in MPa]

Planned public API:
    class StressParams(dataclass): ...
    def restrained_lateral_pressure(heave_strain_field, p) -> np.ndarray  # vectorized, MPa
    def run_restrained_stress_simulation(heave_history, p) -> dict
"""

from dataclasses import dataclass


@dataclass
class StressParams:
    youngs_modulus_frozen: float = 45.0e6   # [Pa] frozen soil elastic modulus (typical, low-strain)
    poisson_ratio_frozen: float = 0.35      # [-]
    restraint_factor_beta: float = 0.8      # [-] fraction of full kinematic restraint (0=free, 1=fully restrained)
    allowable_liner_pressure_mpa: float = 3.0  # [MPa] design/critical threshold for alert_system


def run_restrained_stress_simulation(*args, **kwargs):
    raise NotImplementedError(
        "Module 4 (Thermo-Elastic Restrained Stress) is scheduled for the next "
        "development phase. This stub preserves the API contract consumed by app.py."
    )
